services:
  fastapi:
    build:
      context: .
    container_name: fastapi
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - rede_todolist
      - rede_todolist_db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
    depends_on:
      - mysql
  
  mysql:
    image: mysql
    restart: always
    container_name: mysqlteste
    environment:
      MYSQL_ROOT_PASSWORD: 5912
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - rede_todolist_db

volumes:
  mysql_data:

networks:
  rede_todolist:
    external: true
  rede_todolist_db:
    driver: bridge
